# A first workflow to play around with the editor
name: My First Workflow
on:
  push:
    branches: 
      - main
  workflow_dispatch:

jobs:
  first_job:
    name: My first job
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Hello World 👋 from ${{ github.actor }}." 
          echo "Current branch is 🤫 '${{ github.ref }}'."
      - run: |
          echo "Hello ${{ vars.WHO_TO_GREET }} from ${{ github.actor }}."
          echo "My secret is ${{ secrets.MY_SECRET }}."
      - name: Checkout
        uses: actions/checkout@v6.0.2
      - run: tree 
